### ISSUE TITLE
Is there a way to resolve ILog?

### ISSUE THREAD

**Issue by Ali-Nass** [unitycontainer/log4net#1]
So I have a class that I can't pass any parameters in its constructor so instead of the usual 
```
public class test
{
    private ILog logger;
    public test (ILog logger)
    {
        this.logger =logger;
    }
}
```
I'm trying to achieve something like this
```
public class test
{
    private ILog logger;

    public test()
    {
        logger = unityContainer.Resolve<ILog>(); //
    }
}
```
But trying it out, unity failed to resolve ILog so is there a way to solve this?

**Comment by ENikS** [comment]
You could all apply dependency attributes to a property

**Comment by Ali-Nass** [comment]
Passing ILog to my constructor is working perfectly like 

```
public class test
{
    private ILog logger;
    public test (ILog logger)
    {
        this.logger =logger;
    }
}
```

But I have a class with no constructor and I can't pass the logger to it. Is there a way to resolve such an issue? I tried the following but it failed miserably 

```
public ILog GetLogger()
{
    return DIContainer.Container.Resolve<ILog>();
}
```

**Comment by ENikS** [comment]
Unity uses name of resolved type to initialize logger properly. Something like this:
``log4net.LogManager.GetLogger("MyClass");``

If you want to get arbitrary logger you could just use ``log4net.LogManager.GetLogger``
