### ISSUE TITLE
Problem resolving Ilog in a windows service

### ISSUE THREAD

**Issue by Wolfteam** [unitycontainer/log4net#2]
Hi, im using unity to resolve some dependencies in my windows service.
The win service starts 1 quartz job (https://github.com/quartznet/quartznet). 
To resolve the job dependencies im using this extension https://github.com/hbiarge/Quartz.Unity

For some reason, the ilog dependency in the job gets resolved using the wrong logger. Instead of giving me the logger for SendByEmailJob it gives me the one used in the main service 

    public class SendByEmailJob : IJob
    {
        private readonly ILog _logger;
        private readonly IDistributionLogRepository _distRepo;

        public SendByEmailJob(ILog log, IDistributionLogRepository distRepo)
        {
            _logger = log;
            _distRepo = distRepo;
        }

        public async Task Execute(IJobExecutionContext context)
        {
            _logger.Info("Starting job");
            var emailDist = await _distRepo.GetAll(DeliveryType.Email, DistributionStatusType.Ready);
            var dist = await _distRepo.Get(100);
            foreach (var item in emailDist)
            {
                System.Diagnostics.Debug.WriteLine($"DistributionId = {item.Id}");
            }
            _logger.Info("Job completed");
        }
    }

So checking the Log4NetExtension class, i notice that changing the following method:

        public ResolveDelegate<BuilderContext> GetResolver(ref BuilderContext context)
        {
            Type declaringType = context.DeclaringType;

            return (ref BuilderContext c) => LogManager.GetLogger(declaringType);
        }

To this:

        public ResolveDelegate<BuilderContext> GetResolver(ref BuilderContext context)
        {
            return (ref BuilderContext c) => {
                return LogManager.GetLogger(c.DeclaringType);
            };
        }

Solves the problem and the loggers gets correctly resolved

**Comment by ENikS** [comment]
Why don’t you send a pull request and solve it for others as well?

**Comment by Wolfteam** [comment]
> Why don’t you send a pull request and solve it for others as well?

done

**Comment by kobi2294** [comment]
Well Done!
