### ISSUE TITLE
Injected logger has an unrelated name

### ISSUE THREAD

**Issue by stop-cran** [unitycontainer/log4net#3]
There is an issue, when resolving a graph of objects with injecting `ILog` in several places. For example see following code:

```
class A
{
    public A(B b, ILog logger)
    {
        // Injected with logger.Logger.Name is "ConsoleApp1.B" too.
    }
}

class B
{
    public B(ILog logger)
    {
        // Injected with logger.Logger.Name is "ConsoleApp1.B".
    }
}
```

Resolution code:
```
new UnityContainer()
    .AddNewExtension<Log4NetExtension>()
    .Resolve<A>();
```

Is it done intentionally? I'd expect to inject loggers with corresponding names in both case - `A` and `B`.

**Comment by ENikS** [comment]
If you create a Unit Test I could run I will be able to fix it

**Comment by Dykam** [comment]
@ENikS, would it be possible to release this fix to Nuget? We were running into the same issue.

**Comment by ENikS** [comment]
Unfortunately it would have to wait for 5.11
I've [tried](https://ci.appveyor.com/project/unitycontainer/log4net/builds/25140321) to release it but it requires container to be updated as well. The actual fix is in the container code.

**Comment by Dykam** [comment]
Ah, I see. Do you have an ETA on when this would be? Or a workaround in the mean time?

**Comment by ENikS** [comment]
Hoping to do it soon(ish). Perhaps next week or the week after.
